Development
Skidle613/marketplace pull request #2
Opened 2024-11-12 20:59 UTC by Skidle613

final version of project

2024-11-18 18:51 UTC, dKosarevsky requested changes
необходимо:

- поправить код по комментам к ревью
- добавить инструкцию по запуску приложения
- комментарии к методам оформить в виде docstr
- избыточные комментарии - удалить
- написать тесты
- добавить test coverage
- запуск тестов в GA
- отображать плашку coverage в ридми

2024-12-15 17:39 UTC, Skidle613 commented
Вроде всё порезолвил, но в любом случае актуальная версия висит в ветке development. Всё что просили сделал, кроме возможности запуска тестов в GA. Переделывать увы уже не буду, можете тогда просто оценку снизить

2024-12-15 18:12 UTC, Skidle613 commented
Там кстати еще и покрытие 81%, но почему то плашка никак не хочет обновляться

2024-12-15 21:03 UTC, dKosarevsky approved these changes

2024-12-15 21:03 UTC, merged